import './globals.scss'
import { Inter } from 'next/font/google'
import {ReactNode} from "react";
import {Footer, Header} from "@/components";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative flex flex-col justify-between items-center h-screen bg-gray-50 ${inter.className}`}>
      <Header/>
      <main className="flex-1 w-full">
        {children}
      </main>
      <Footer/>
      </body>
    </html>
  )
}
